from __future__ import annotations

from typing import Any

from bumpkin.providers.llm_recommend_types import (
    AggregateChunkRecommendationsFn,
    CallModelFn,
    ClassifiedResultFn,
    GetStubRecommendationFn,
    ManualReviewResultFn,
    ProviderModeFn,
    RecommendationCallbacks,
    RecommendationRequest,
    SemanticFallbackFn,
    SplitDiffIntoChunksFn,
    SplitDiffUnitsIntoChunksFn,
    WithChunkingMetadataFn,
)
from bumpkin.providers.llm_strategy import RecommendationStrategy


def get_recommendation(
    *,
    provider_mode_for_endpoint_fn: ProviderModeFn,
    get_stub_recommendation_fn: GetStubRecommendationFn,
    split_diff_units_into_chunks_fn: SplitDiffUnitsIntoChunksFn,
    split_diff_into_chunks_fn: SplitDiffIntoChunksFn,
    call_model_fn: CallModelFn,
    aggregate_chunk_recommendations_fn: AggregateChunkRecommendationsFn,
    classified_result_fn: ClassifiedResultFn,
    manual_review_result_fn: ManualReviewResultFn,
    semantic_fallback_fn: SemanticFallbackFn,
    with_chunking_metadata_fn: WithChunkingMetadataFn,
    mode: str,
    diff_text: str,
    truncated: bool,
    language_group: str | None,
    prompt_version: str | None,
    surface_area_hints: list[str] | None,
    language_hints: list[str] | None,
    model: str,
    fallback_model: str | None,
    endpoint: str,
    token: str,
    use_semantic_fallback: bool = True,
    max_retries: int = 3,
    request_timeout: int = 45,
    chunking_enabled: bool = True,
    chunk_max_tokens: int = 1200,
    chunk_max_count: int = 24,
    chunk_failure_policy: str = "MANUAL_REVIEW",
    diff_units: list[tuple[str, str]] | None = None,
) -> tuple[dict[str, Any], str, str | None, str | None]:
    callbacks = RecommendationCallbacks(
        provider_mode_for_endpoint=provider_mode_for_endpoint_fn,
        get_stub_recommendation=get_stub_recommendation_fn,
        split_diff_units_into_chunks=split_diff_units_into_chunks_fn,
        split_diff_into_chunks=split_diff_into_chunks_fn,
        call_model=call_model_fn,
        aggregate_chunk_recommendations=aggregate_chunk_recommendations_fn,
        classified_result=classified_result_fn,
        manual_review_result=manual_review_result_fn,
        semantic_fallback=semantic_fallback_fn,
        with_chunking_metadata=with_chunking_metadata_fn,
    )
    request = RecommendationRequest(
        mode=mode,
        diff_text=diff_text,
        truncated=truncated,
        language_group=language_group,
        prompt_version=prompt_version,
        surface_area_hints=surface_area_hints,
        language_hints=language_hints,
        model=model,
        fallback_model=fallback_model,
        endpoint=endpoint,
        token=token,
        use_semantic_fallback=use_semantic_fallback,
        max_retries=max_retries,
        request_timeout=request_timeout,
        chunking_enabled=chunking_enabled,
        chunk_max_tokens=chunk_max_tokens,
        chunk_max_count=chunk_max_count,
        chunk_failure_policy=chunk_failure_policy,
        diff_units=diff_units,
    )
    return RecommendationStrategy(callbacks).run(request)
