"""Compatibility facade for Python API signature and constructor analysis."""

from .python_signature_context import (
    PythonFunctionSignature,
    classify_nested_python_constructor_context,
    classify_nested_python_constructor_context_from_hunk,
    has_ambiguous_python_constructor_match,
    infer_python_constructor_class_from_workspace,
    infer_python_member_class_from_workspace,
    is_public_python_member_symbol,
    match_python_member_renames,
    python_class_scope_is_public,
    python_public_class_path,
    python_statement_anchor,
    python_symbol_roots,
    signature_key,
    signatures_equivalent,
)
from .python_signature_extraction import (
    collect_python_decorator_names,
    collect_python_signature_block,
    extract_python_classes,
    extract_python_signatures,
    is_public_python_member_name,
    iter_python_version_lines,
    python_method_kind_from_decorators,
)

__all__ = [
    "PythonFunctionSignature",
    "classify_nested_python_constructor_context",
    "classify_nested_python_constructor_context_from_hunk",
    "collect_python_decorator_names",
    "collect_python_signature_block",
    "extract_python_classes",
    "extract_python_signatures",
    "has_ambiguous_python_constructor_match",
    "infer_python_constructor_class_from_workspace",
    "infer_python_member_class_from_workspace",
    "is_public_python_member_name",
    "is_public_python_member_symbol",
    "iter_python_version_lines",
    "match_python_member_renames",
    "python_class_scope_is_public",
    "python_method_kind_from_decorators",
    "python_public_class_path",
    "python_statement_anchor",
    "python_symbol_roots",
    "signature_key",
    "signatures_equivalent",
]
